apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager-prometheus-discovery
  labels:
    k8s-app: kube-controller-manager
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    k8s-app: kube-controller-manager
  type: ClusterIP
  clusterIP: None
  ports:
  - name: prometheus
    port: 10252
    targetPort: 10252
    protocol: TCP
