global:
  evaluation_interval: 15s
  scrape_interval: 15s

rule_files:
- /etc/prometheus/rules/*.rules

scrape_configs:
- job_name: standard-endpoints
  kubernetes_sd_configs:
  - role: endpoints

  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    # As for kubelets, certificate validation fails for the API server (node)
    # and we circumvent it for now.
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  relabel_configs:
  - action: keep
    source_labels: [__meta_kubernetes_service_name]
    regex: prometheus
  - action: replace
    source_labels: [__meta_kubernetes_service_name]
    target_label: job
  - action: replace
    source_labels: [__meta_kubernetes_service_name]
    regex: kubernetes
    target_label: __scheme__
    replacement: https
